name: keyboard_utils_fork
description: fork from https://github.com/IsaiasSantana/keyboard_utils
version: 0.0.4
homepage: https://github.com/hello-coder-xu/keyboard_utils.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dependencies_override:
  sky_engine:
    path: /Users/10457/flutter_engine/engine/src/out/host_debug_unopt_arm64/gen/dart-pkg/sky_engine

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: br.com.keyboard_utils
        pluginClass: KeyboardUtilsPlugin
      ios:
        pluginClass: SwiftKeyboardUtilsPlugin
